### ISSUE TITLE
Create MVC for Business Application Phase

### ISSUE THREAD

**Issue by edmundchan8** [Cascadia-Connections/orca-stars#11]
A business would have a web form to fill in their business details, an option to download the 'checklist'.  When this form is completed, a notification goes to the orcastars conservancy team to let them know of a pending application, so that they can go out to view the site.  

Once approved, the data is submitted to the database, if disapproved, the application is gotten rid of.

**Comment by Bansenauer-Cascadia** [comment]
This idea is more like a Product Backlog feature statement, rather than an issue. 
Issues should be described in the work that you need to do as a developer to make the result happen. The scope of the work should be able to be completed during a Sprint by one person.
Move this to the Product Backlog and assign it a priority based on the stakeholder's interest in it.

**Comment by edmundchan8** [comment]
Archiving and moving idea to product backlog
