### ISSUE TITLE
Draft of structure of code - Classes, models, naming conventions

### ISSUE THREAD

**Issue by edmundchan8** [Cascadia-Connections/orca-stars#8]
Issue Description: Draft structure of the code for the project

DOD: Create a first draft for guidelines with code formatting, naming conventions, and file structure.

Use Case: Developers working to contribute towards this project will have a formatting guide to aid them in their coding including structure and naming conventions.

**Comment by Bansenauer-Cascadia** [comment]
Nice use of the label to highlight documentation.

The DoD is too general to be useful in deciding whether the issue is complete.
I think you may be struggling to define the DoD because your task is too broad. A "living document" is never really complete, so perhaps reframe this task as "creating an initial draft with example guidelines in at least these areas, code formatting, naming conventions, ..." 

Each issue should be framed so that it could be completed in a single Sprint - if not, break it into smaller bits.
